version: "3.8"
services:
  app:
    build:
      context: .
      target: dev
    env_file: ./.env.local
    command: npm start
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/
    ports:
      - 8080:8080

    environment:
      NODE_ENV: dev
      VIRTUAL_PORT: 8080

volumes:
  static_volume:
